// <auto-generated />
using System;
using DaftarSekolahCRUD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaftarSekolahCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217133254_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Extracurricular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Extracurriculars");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentExtracurricular", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExtracurricularId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "ExtracurricularId");

                    b.HasIndex("ExtracurricularId");

                    b.ToTable("StudentExtracurriculars");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Student", b =>
                {
                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentExtracurricular", b =>
                {
                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.Extracurricular", "Extracurricular")
                        .WithMany("StudentExtracurriculars")
                        .HasForeignKey("ExtracurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.Student", "Student")
                        .WithMany("StudentExtracurriculars")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extracurricular");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("DaftarSekolahCRUD.Domain.Entities.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Extracurricular", b =>
                {
                    b.Navigation("StudentExtracurriculars");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Student", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("StudentExtracurriculars");
                });
#pragma warning restore 612, 618
        }
    }
}
