// <auto-generated />
using System;
using DaftarSekolahCRUD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaftarSekolahCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214195430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "X IPA"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Name = "X IPS"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Name = "X Bahasa"
                        });
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Extracurricular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Extracurriculars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Name = "Basket"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            Name = "Futsal"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            Name = "Pramuka"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123456"),
                            Name = "Robotics"
                        });
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentExtracurricular", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExtracurricularId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "ExtracurricularId");

                    b.HasIndex("ExtracurricularId");

                    b.ToTable("StudentExtracurriculars");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Student", b =>
                {
                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentExtracurricular", b =>
                {
                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.Extracurricular", "Extracurricular")
                        .WithMany("StudentExtracurriculars")
                        .HasForeignKey("ExtracurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.Student", "Student")
                        .WithMany("StudentExtracurriculars")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extracurricular");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("DaftarSekolahCRUD.Domain.Entities.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("DaftarSekolahCRUD.Domain.Entities.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Extracurricular", b =>
                {
                    b.Navigation("StudentExtracurriculars");
                });

            modelBuilder.Entity("DaftarSekolahCRUD.Domain.Entities.Student", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("StudentExtracurriculars");
                });
#pragma warning restore 612, 618
        }
    }
}
