// <auto-generated />
using System;
using FormulirPendaftaranSekolahCRUD.Helper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulirPendaftaranSekolahCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FormulirPendaftaranSekolahCRUD.Model.Kelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaKelas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kelass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deskripsi = "Ilmu Pengetahuan Alam",
                            NamaKelas = "IPA"
                        },
                        new
                        {
                            Id = 2,
                            Deskripsi = "Ilmu Pengetahuan Sosial",
                            NamaKelas = "IPS"
                        });
                });

            modelBuilder.Entity("FormulirPendaftaranSekolahCRUD.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KelasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaOrangTua")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KelasId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FormulirPendaftaranSekolahCRUD.Model.Student", b =>
                {
                    b.HasOne("FormulirPendaftaranSekolahCRUD.Model.Kelas", "Kelas")
                        .WithMany("Students")
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelas");
                });

            modelBuilder.Entity("FormulirPendaftaranSekolahCRUD.Model.Kelas", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
